import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sider from "@/components/Sider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gemini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <Sider />
          <div className="w-full">
            <Header />
            <div className="overflow-auto scroobar-styles bg-white">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
